# Generated by Django 4.2.2 on 2023-08-04 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('user_name', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('password', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('url', models.URLField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inbound',
            fields=[
                ('enable', models.IntegerField(blank=True, default='', null=True)),
                ('remark', models.CharField(default='', max_length=256)),
                ('total', models.IntegerField(blank=True, default='', null=True)),
                ('expiry_time', models.IntegerField(blank=True, default='', null=True)),
                ('port', models.IntegerField(blank=True, default='', null=True)),
                ('uuid', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('up', models.IntegerField(blank=True, default='', null=True)),
                ('down', models.IntegerField(blank=True, default='', null=True)),
                ('id', models.IntegerField(blank=True, default='', null=True)),
                ('user_id', models.IntegerField(blank=True, default='', null=True)),
                ('listen', models.TextField(blank=True, default='', null=True)),
                ('protocol', models.TextField(blank=True, default='', null=True)),
                ('settings', models.TextField(blank=True, default='', null=True)),
                ('stream_settings', models.TextField(blank=True, default='', null=True)),
                ('tag', models.TextField(blank=True, default='', null=True)),
                ('sniffing', models.TextField(blank=True, default='', null=True)),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datarefresher.server')),
            ],
        ),
    ]
