# Generated by Django 4.2.2 on 2023-08-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datarefresher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='ip',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
