# Generated by Django 4.2.2 on 2023-08-05 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datarefresher', '0002_server_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbound',
            name='user_id',
        ),
    ]
