# Generated by Django 4.2.2 on 2023-08-17 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presenter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchased',
            old_name='user',
            new_name='buyer',
        ),
        migrations.RenameField(
            model_name='purchased',
            old_name='inbound_id',
            new_name='user_id',
        ),
    ]
