# Generated by Django 4.2.2 on 2024-02-04 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presenter', '0002_rename_user_purchased_buyer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchased',
            old_name='buyer',
            new_name='seller',
        ),
    ]
