# Generated by Django 4.2.2 on 2024-02-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presenter', '0003_rename_buyer_purchased_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('user_name', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('password', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('ip', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('url', models.URLField(blank=True, default='', null=True)),
            ],
        ),
    ]
