# Generated by Django 4.2.2 on 2024-02-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presenter', '0005_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='email',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
