# Generated by Django 4.2.2 on 2024-02-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modifier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updated_inbound',
            name='expiry_time',
            field=models.DateTimeField(blank=True, default='', null=True),
        ),
    ]
