# Generated by Django 4.2.2 on 2024-02-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modifier', '0002_alter_updated_inbound_expiry_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='updated_inbound',
            name='uuid',
            field=models.CharField(default='', max_length=256),
        ),
    ]
